"""paquete abastecimiento: proveedores, ordenes de compra y recepciones

Revision ID: 14ba109668a9
Revises: 3ecfa26bb535
Create Date: 2026-08-29 18:21:28.645529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.inventario.repository import VW_INVENTARIO_CONSOLIDADO_SQL


# revision identifiers, used by Alembic.
revision: str = '14ba109668a9'
down_revision: Union[str, None] = '3ecfa26bb535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('orden_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_esperada', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('borrador','enviada','parcial','recibida','anulada')", name='ck_orden_compra_estado'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('producto_proveedor',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('costo_referencial', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dias_entrega', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proveedor_id', 'producto_id')
    )
    op.create_table('recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('orden_compra_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_orden_compra_detalle_cantidad'),
    sa.CheckConstraint('costo_unitario >= 0', name='ck_orden_compra_detalle_costo'),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['orden_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_compra_id', 'variante_id', name='uq_orden_compra_detalle_variante')
    )
    op.create_table('recepcion_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_recepcion_detalle_cantidad'),
    sa.CheckConstraint('costo_unitario >= 0', name='ck_recepcion_detalle_costo'),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepcion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Vista de docs/fashionstore_esquema.sql, la usa GET /api/v1/inventario/
    # consolidado y /alertas. No la genera autogenerate (no es una tabla
    # mapeada), así que se crea a mano acá.
    op.execute(VW_INVENTARIO_CONSOLIDADO_SQL)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS vw_inventario_consolidado")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepcion_detalle')
    op.drop_table('orden_compra_detalle')
    op.drop_table('recepcion')
    op.drop_table('producto_proveedor')
    op.drop_table('orden_compra')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
