"""paquete reservas y notificaciones

Revision ID: 2cb318fc993b
Revises: 14ba109668a9
Create Date: 2026-08-29 19:25:05.358761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb318fc993b'
down_revision: Union[str, None] = '14ba109668a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=25), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('mensaje', sa.String(length=400), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=False),
    sa.Column('hora_visita_desde', sa.Time(), nullable=False),
    sa.Column('hora_visita_hasta', sa.Time(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hora_visita_hasta > hora_visita_desde', name='ck_reserva_horas'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_reserva.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('reserva_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_reserva.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('seleccionada', sa.Boolean(), nullable=True),
    sa.Column('preparada', sa.Boolean(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_reserva_detalle_cantidad'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', 'variante_id', name='uq_reserva_detalle_variante')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_detalle')
    op.drop_table('reserva_historial')
    op.drop_table('reserva')
    op.drop_table('notificacion')
    op.drop_table('estado_reserva')
    # ### end Alembic commands ###
