"""recomendador

Revision ID: 2e3c82098813
Revises: 024024d004fc
Create Date: 2026-09-08 12:02:33.480418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3c82098813'
down_revision: Union[str, None] = '024024d004fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_navegacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('sesion_anonima', sa.String(length=64), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=25), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_evento IN ('vista','busqueda','carrito','probador','favorito')", name='ck_historial_navegacion_tipo_evento'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('generado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomendacion')
    op.drop_table('historial_navegacion')
    # ### end Alembic commands ###
