"""paquete inventario: stock y movimientos

Revision ID: 3ecfa26bb535
Revises: d7b99a3dbdb0
Create Date: 2026-08-29 17:55:18.756721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecfa26bb535'
down_revision: Union[str, None] = 'd7b99a3dbdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=25), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('signo', sa.SmallInteger(), nullable=False),
    sa.Column('afecta_costo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('signo IN (-1, 1)', name='ck_tipo_movimiento_signo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('sucursal_origen_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_destino_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente','en_transito','recibida','anulada')", name='ck_transferencia_estado'),
    sa.CheckConstraint('sucursal_origen_id <> sucursal_destino_id', name='ck_transferencia_sucursales'),
    sa.ForeignKeyConstraint(['sucursal_destino_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['sucursal_origen_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('costo_promedio_post', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('saldo_post', sa.Integer(), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=25), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad <> 0', name='ck_movimiento_cantidad'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['tipo_movimiento_id'], ['tipo_movimiento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_fisica', sa.Integer(), nullable=False),
    sa.Column('cantidad_reservada', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), sa.Computed('cantidad_fisica - cantidad_reservada', persisted=True), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('costo_promedio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_fisica >= 0', name='ck_stock_cantidad_fisica'),
    sa.CheckConstraint('cantidad_reservada <= cantidad_fisica', name='ck_stock_reservada_no_supera_fisica'),
    sa.CheckConstraint('cantidad_reservada >= 0', name='ck_stock_cantidad_reservada'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variante_id', 'sucursal_id', name='uq_stock_variante_sucursal')
    )
    op.create_table('transferencia_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_transferencia_detalle_cantidad'),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencia_detalle')
    op.drop_table('stock')
    op.drop_table('movimiento_inventario')
    op.drop_table('transferencia')
    op.drop_table('tipo_movimiento')
    # ### end Alembic commands ###
