"""paquete ventas

Revision ID: 47f72131c7ff
Revises: 9000225565be
Create Date: 2026-08-30 17:56:21.801113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f72131c7ff'
down_revision: Union[str, None] = '9000225565be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=25), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('porcentaje','monto')", name='ck_promocion_tipo'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_promocion_fechas'),
    sa.CheckConstraint('valor > 0', name='ck_promocion_valor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_table('promocion_alcance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # num_nonnulls() es de Postgres, no existe en SQLite (lo que usan los
    # tests): por eso este CHECK se agrega a mano acá en vez de vivir en
    # PromocionAlcance.__table_args__. La regla ("exactamente uno de
    # producto_id/categoria_id/temporada_id") también se valida en
    # ventas.service antes de insertar.
    op.execute(
        "ALTER TABLE promocion_alcance ADD CONSTRAINT ck_promocion_alcance_un_solo_alcance "
        "CHECK (num_nonnulls(producto_id, categoria_id, temporada_id) = 1)"
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=15), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=True),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("canal <> 'presencial' OR cajero_id IS NOT NULL", name='ck_venta_cajero_presencial'),
    sa.CheckConstraint("canal IN ('digital','presencial')", name='ck_venta_canal'),
    sa.ForeignKeyConstraint(['cajero_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_venta.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('carrito_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_carrito_detalle_cantidad'),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrito_id', 'variante_id', name='uq_carrito_detalle_variante')
    )
    op.create_table('devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente','aprobada','rechazada')", name='ck_devolucion_estado'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_venta_detalle_cantidad'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucion_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('venta_detalle_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_devolucion_detalle_cantidad'),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devolucion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_detalle_id'], ['venta_detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devolucion_detalle')
    op.drop_table('venta_detalle')
    op.drop_table('devolucion')
    op.drop_table('carrito_detalle')
    op.drop_table('venta')
    op.execute("ALTER TABLE promocion_alcance DROP CONSTRAINT ck_promocion_alcance_un_solo_alcance")
    op.drop_table('promocion_alcance')
    op.drop_table('carrito')
    op.drop_table('promocion')
    op.drop_table('estado_venta')
    # ### end Alembic commands ###
