"""paquete catalogo - producto y variantes

Revision ID: 65f2cb850b71
Revises: 3b335f150374
Create Date: 2026-08-29 00:18:47.685310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f2cb850b71'
down_revision: Union[str, None] = '3b335f150374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('coleccion_id', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=15), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('admite_probador', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.CheckConstraint("genero IN ('hombre','mujer','unisex','nino')", name='ck_producto_genero'),
    sa.CheckConstraint('precio_base >= 0', name='ck_producto_precio_base'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['coleccion_id'], ['coleccion.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporada.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('producto_imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_variante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('talla_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('codigo_barras', sa.String(length=40), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('precio IS NULL OR precio >= 0', name='ck_variante_precio'),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talla_id'], ['talla.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('producto_id', 'talla_id', 'color_id', name='uq_variante_producto_talla_color'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('tabla_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('talla_id', sa.Integer(), nullable=False),
    sa.Column('pecho_min_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pecho_max_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('cintura_min_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('cintura_max_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hombros_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('largo_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.CheckConstraint('producto_id IS NOT NULL OR categoria_id IS NOT NULL', name='ck_tabla_medida_producto_o_categoria'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talla_id'], ['talla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabla_medida')
    op.drop_table('producto_variante')
    op.drop_table('producto_imagen')
    op.drop_table('producto')
    # ### end Alembic commands ###
