"""paquete probador backend de uso

Revision ID: 9000225565be
Revises: 2cb318fc993b
Create Date: 2026-08-29 23:34:24.688694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9000225565be'
down_revision: Union[str, None] = '2cb318fc993b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probador_generacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('hash_foto', sa.String(length=64), nullable=False),
    sa.Column('url_resultado', sa.Text(), nullable=True),
    sa.Column('proveedor', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('mensaje_error', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('en_proceso','completado','fallido')", name='ck_probador_generacion_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generacion_cache', 'probador_generacion', ['hash_foto', 'variante_id'], unique=False)
    op.create_table('sesion_probador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.String(length=15), nullable=False),
    sa.Column('duracion_seg', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modo IN ('espejo','generativo')", name='ck_sesion_probador_modo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesion_probador')
    op.drop_index('ix_generacion_cache', table_name='probador_generacion')
    op.drop_table('probador_generacion')
    # ### end Alembic commands ###
