"""paquete entregas

Revision ID: 9f974d918aae
Revises: f5b676ec5a74
Create Date: 2026-08-30 19:35:32.007953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f974d918aae'
down_revision: Union[str, None] = 'f5b676ec5a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('anillo_desde', sa.SmallInteger(), nullable=True),
    sa.Column('anillo_hasta', sa.SmallInteger(), nullable=True),
    sa.Column('tarifa_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('tarifa_base >= 0', name='ck_zona_envio_tarifa_base'),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direccion_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('zona_envio_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zona_envio_id'], ['zona_envio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regla_tarifa_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zona_envio_id', sa.Integer(), nullable=False),
    sa.Column('peso_desde_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('peso_hasta_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recargo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['zona_envio_id'], ['zona_envio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('zona_envio_id', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('repartidor', sa.String(length=80), nullable=True),
    sa.CheckConstraint("estado IN ('programado','en_ruta','entregado','fallido')", name='ck_envio_estado'),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion_cliente.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.ForeignKeyConstraint(['zona_envio_id'], ['zona_envio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envio')
    op.drop_table('regla_tarifa_envio')
    op.drop_table('direccion_cliente')
    op.drop_table('zona_envio')
    # ### end Alembic commands ###
