"""paquete probador - editor de anclajes

Revision ID: d7b99a3dbdb0
Revises: f29fa6c11a97
Create Date: 2026-08-29 01:02:45.681123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7b99a3dbdb0'
down_revision: Union[str, None] = 'f29fa6c11a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activo_probador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('anclajes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ancho_px', sa.Integer(), nullable=True),
    sa.Column('alto_px', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','validado','rechazado')", name='ck_activo_probador_estado'),
    sa.CheckConstraint("tipo IN ('overlay_2d','flatlay_ia','thumb')", name='ck_activo_probador_tipo'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_activo_variante_tipo', 'activo_probador', ['variante_id', 'tipo'], unique=True, postgresql_where=sa.text("estado <> 'rechazado'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_activo_variante_tipo', table_name='activo_probador', postgresql_where=sa.text("estado <> 'rechazado'"))
    op.drop_table('activo_probador')
    # ### end Alembic commands ###
