"""paquete catalogo - catalogo publico, favoritos e indices

Revision ID: f29fa6c11a97
Revises: 65f2cb850b71
Create Date: 2026-08-29 00:49:50.587569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29fa6c11a97'
down_revision: Union[str, None] = '65f2cb850b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cliente_id', 'variante_id')
    )
    op.create_index('ix_producto_categoria', 'producto', ['categoria_id'], unique=False, postgresql_where=sa.text('activo'))
    op.create_index('ix_producto_genero', 'producto', ['genero', 'categoria_id'], unique=False, postgresql_where=sa.text('activo'))
    op.create_index('ix_producto_temporada', 'producto', ['temporada_id'], unique=False, postgresql_where=sa.text('activo'))
    op.create_index('ix_variante_producto', 'producto_variante', ['producto_id'], unique=False, postgresql_where=sa.text('activo'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variante_producto', table_name='producto_variante', postgresql_where=sa.text('activo'))
    op.drop_index('ix_producto_temporada', table_name='producto', postgresql_where=sa.text('activo'))
    op.drop_index('ix_producto_genero', table_name='producto', postgresql_where=sa.text('activo'))
    op.drop_index('ix_producto_categoria', table_name='producto', postgresql_where=sa.text('activo'))
    op.drop_table('favorito')
    # ### end Alembic commands ###
