"""paquete pagos

Revision ID: f5b676ec5a74
Revises: 47f72131c7ff
Create Date: 2026-08-30 18:33:27.568702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5b676ec5a74'
down_revision: Union[str, None] = '47f72131c7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=25), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=25), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('requiere_pasarela', sa.Boolean(), nullable=False),
    sa.Column('disponible_caja', sa.Boolean(), nullable=False),
    sa.Column('disponible_online', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_externa', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto > 0', name='ck_pago_monto'),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_pago.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion_pasarela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('pasarela', sa.String(length=30), nullable=False),
    sa.Column('id_transaccion', sa.String(length=120), nullable=True),
    sa.Column('payload_envio', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_respuesta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estado', sa.String(length=25), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaccion_pasarela')
    op.drop_table('pago')
    op.drop_table('metodo_pago')
    op.drop_table('estado_pago')
    # ### end Alembic commands ###
